# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SYC\Desktop\code\pyqtprojectfinall\qtaddpt\banben1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QFileDialog, QApplication, QTableWidgetItem
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from PIL import Image

import cv2
import adp
import detect
import time

file_path = ""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -40, 591, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(620, 30, 400, 676))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        # self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        # self.checkBox.setObjectName("checkBox")
        # self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        # self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        # self.checkBox_2.setObjectName("checkBox_2")
        # self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        # self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        # self.checkBox_3.setObjectName("checkBox_3")
        # self.horizontalLayout_4.addWidget(self.checkBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 190, 591, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(self.apiaddpoint)  # type: ignore
        self.pushButton.clicked.connect(self.addfile)  # type: ignore
        self.pushButton_2.clicked.connect(self.playvideo)  # type: ignore
        self.pushButton_3.clicked.connect(self.pausevedio) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label_7.resize(10, 30)
        # pix = QtGui.QPixmap('/Users/lycoris/Desktop/contest/互联网+/yolov7/yolov7/pict/1.jpg')
        # # pix = QtGui.QPixmap("first_frame.png")
        # self.label_7.setPixmap(pix)
        # self.label_7.setScaledContents(True)

        self.label_8.resize(10, 30)
        # pix = QtGui.QPixmap('/Users/lycoris/Desktop/contest/互联网+/yolov7/yolov7/pict/2.jpg')
        # # pix = QtGui.QPixmap("first_frame.png")
        # self.label_8.setPixmap(pix)
        # self.label_8.setScaledContents(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "路边车辆停车检测"))
        self.pushButton.setText(_translate("MainWindow", "打开视频"))
        self.pushButton_2.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_3.setText(_translate("MainWindow", "结束检测"))
        self.pushButton_4.setText(_translate("MainWindow", "选定车位"))
        self.label.setText(_translate("MainWindow", "车位1"))
        # self.checkBox.setText(_translate("MainWindow", "有无停车"))
        self.label_4.setText(_translate("MainWindow", "picture1"))
        self.label_2.setText(_translate("MainWindow", "车位2"))
        # self.checkBox_2.setText(_translate("MainWindow", "有无停车"))
        self.label_5.setText(_translate("MainWindow", "picture2"))
        self.label_3.setText(_translate("MainWindow", "车位3"))
        # self.checkBox_3.setText(_translate("MainWindow", "有无停车"))
        self.label_6.setText(_translate("MainWindow", "picture3"))
        self.label_7.setText(_translate("MainWindow", "play1"))
        self.label_8.setText(_translate("MainWindow", "play2"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+Q"))

    def apiaddpoint(self):
        import adp
        adp.addpoint()

    def addfile(self):
        global file_path
        file_path = QFileDialog.getOpenFileName()[0]
        adp.first_frame(file_path)
        self.refreshimg7()
        print(file_path)
        # lineEdit.setText(file_path)  # 获取文件路径
        # self.updateCamInfo(file_path)

    def playvideo(self):
        detect.detect(file_path)

    def refreshimg7(self):  # 接口函数，用来导入视频后，显示处理后的图片

        pix = QtGui.QPixmap("pict/1.jpg")
        # pix = QtGui.QPixmap("first_frame.png ")
        self.label_7.setPixmap(pix)
        self.label_7.setScaledContents(True)
        QApplication.processEvents()

    def refreshimg8(self):  # 接口函数，用来导入视频后，显示处理后的图片
        pix = QtGui.QPixmap("pict/2.jpg")
        # pix = QtGui.QPixmap("first_frame.png")
        self.label_8.setPixmap(pix)
        self.label_8.setScaledContents(True)
        QApplication.processEvents()

    def refreshimg4(self, t):  # 接口函数，用来导入视频后，显示处理后的图片
        if t:
            pix = QtGui.QPixmap("pict/20.jpg")
        else:
            pix = QtGui.QPixmap("pict/2.jpg")
        # pix = QtGui.QPixmap("first_frame.png")
        self.label_4.setPixmap(pix)
        self.label_4.setScaledContents(True)
        QApplication.processEvents()

    def refreshimg5(self, t):  # 接口函数，用来导入视频后，显示处理后的图片
        if t:
            pix = QtGui.QPixmap("pict/21.jpg")
        else:
            pix = QtGui.QPixmap("pict/2.jpg")
        # pix = QtGui.QPixmap("first_frame.png")
        self.label_5.setPixmap(pix)
        self.label_5.setScaledContents(True)
        QApplication.processEvents()

    def refreshimg6(self, t):  # 接口函数，用来导入视频后，显示处理后的图片
        if t:
            pix = QtGui.QPixmap("pict/22.jpg")
        else:
            pix = QtGui.QPixmap("pict/2.jpg")
        # pix = QtGui.QPixmap("first_frame.png")
        self.label_6.setPixmap(pix)
        self.label_6.setScaledContents(True)
        QApplication.processEvents()

    def onChanged1(self, s):
        self.label.setText("车位1" + ("有" if s else "没有") + "车")

    def onChanged2(self, s):
        self.label_2.setText("车位2" + ("有" if s else "没有") + "车")

    def onChanged3(self, s):
        self.label_3.setText("车位3" + ("有" if s else "没有") + "车")

    def pausevedio(self):
        self.quit()


ui = Ui_MainWindow()
